version: '2.1'

services:
    db:
        build:
            context: ./db
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: scrapyDB
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d scrapyDB"]
            interval: 10s
            timeout: 5s
            retries: 5
    spiders:
        build:
            context: ./crawler
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: scrapyDB
        depends_on:
         db:
            condition: service_healthy
    app:
        build:
            context: ./flask-service
        ports:
            - "8080:8080"
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: scrapyDB
        depends_on:
            db:
                condition: service_healthy